language: python
python:
  - "2.7"
before_install:
- openssl aes-256-cbc -K $encrypted_096f46e6f614_key -iv $encrypted_096f46e6f614_iv
  -in client-secret.json.enc -out client-secret.json -d
# install:
# - pip install -r requirements.txt -t lib/
script:
- ./scripts/bootstrap.sh
- make test
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: eng-flux-176109
  default: true
  on: master
