runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/static
- url: /robots.txt
  static_files: app/static/robots.txt
  upload: app/static/robots.txt
- url: /.*
  script: main.application

libraries:
- name: flask
  version: 0.12
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"

skip_files:
- app-dev.yaml

# copy this file and create app-dev.yaml, then uncomment env_variables section 
#
# env_variables:
#   SECRET_KEY: "secret_key"
#   # localhost
#   API_BASE_URL: "http://localhost:5000"
#   ADMIN_CLIENT_ID: "admin"
#   ADMIN_CLIENT_SECRET: "secret"
#   IMAGES_URL: "http://images"
#   # get google creds
#   GOOGLE_OAUTH2_CLIENT_ID: "client id"
#   GOOGLE_OAUTH2_CLIENT_SECRET: "client secret"
#   GOOGLE_OAUTH2_REDIRECT_URI: "http://localhost:8080/oauth2callback"
