runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: app/static
- url: /robots.txt
  static_files: app/static/robots.txt
  upload: app/static/robots.txt
- url: /.*
  script: main.application

libraries:
- name: flask
  version: 0.12
- name: ssl
  version: latest
- name: numpy
  version: "1.6.1"

skip_files:
- app-dev.yaml
