# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ add-github-action ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    # Runs a set of commands using the runners shell
    - name: Run tests
      run: |
        python --version
        pip install --upgrade 'pip==20.3.4'
        pip install virtualenv==16.7.8 flake8==3.7.4 pytest==3.5.0
        # pip install wheel
        virtualenv venv
        source ./venv/bin/activate
        pip install -r requirements.txt
        # pip install --user --install-option="--prefix=" na-api
        # ./scripts/bootstrap.sh

        echo "running tests...."
        make test
